//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoPlayV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportandRec
    {
        public string X { get; set; }
        public string Y { get; set; }
        public string OBJECTID { get; set; }
        public string Facility_ID { get; set; }
        public string FacilityName { get; set; }
        public string StreetNo { get; set; }
        public string StreetName { get; set; }
        public string StreetType { get; set; }
        public string SuburbTown { get; set; }
        public string Postcode { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string FaciltySportPlayedID { get; set; }
        public string SportsPlayed { get; set; }
        public string NumberFieldCourts { get; set; }
        public string FieldSurfaceType { get; set; }
        public string FacilityAge { get; set; }
        public string FacilityCondition { get; set; }
        public string FacilityUpgradeAge { get; set; }
        public string Changerooms { get; set; }
        public string LGA { get; set; }
    }
}
